version: "3.8"
services:
  mysql:
    image: mysql:latest
    container_name: mysql
    volumes:
      - ./mysql:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment: 
      MYSQL_ROOT_PASSWORD: 123123
    ports: 
      - 3307:3306
    networks:
      - ecom
networks:
  ecom:
    driver: bridge
